"""A role override's resolved ``full_name``/``mission`` reaches the item's own top-level
``title``/``description``, not only their ``extra`` mirror, checked against the declared
string itself rather than agreement between the two."""

from pathlib import Path

import pytest

from squads import __version__
from squads import _itemfile as itemfile
from squads._errors import SquadsError
from squads._models._extras import ExtraKey as X
from squads._roles._catalog import PREDEFINED
from squads._services import _maintenance as maintenance
from squads._workflow import ROSTER_ROLE

pytestmark = pytest.mark.anyio

_BUNDLED_ARCHITECT = next(r for r in PREDEFINED if r.slug == "architect")


def _place_override(squad_dir: Path, slug: str, content: str) -> None:
    """Write a stamped ``.overrides/roles/<slug>.toml``."""
    target = squad_dir / ".overrides" / "roles" / f"{slug}.toml"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(f"# squads:override-base:{__version__}\n{content}", encoding="utf-8")


def _on_disk_frontmatter(svc, item) -> dict[str, object]:
    from squads._index._resolver import item_file

    return itemfile.read_frontmatter(text=item_file(svc.paths, item).read_text(encoding="utf-8"))


def _claude_md(project) -> str:
    return (project.root / "CLAUDE.md").read_text(encoding="utf-8")


def _pointer_text(project, slug: str) -> str:
    return (project.root / ".claude" / "agents" / f"{slug}.md").read_text(encoding="utf-8")


async def _list_title(svc, item_id: str) -> str:
    items = await svc.list_items(item_type=ROSTER_ROLE)
    return next(it.title for it in items if it.id == item_id)


# --------------------------------------------------------------------------------------------
# Pair 1: full_name -> title, bundled role.
# --------------------------------------------------------------------------------------------


async def test_bundled_role_declared_full_name_reaches_title_on_every_surface(project, svc):
    role = await svc.activate_role("architect")
    _place_override(project.squad_dir, "architect", 'full_name = "Ada Lovelace"\n')

    skipped = await svc.sync()
    assert skipped == [
        ".claude/agents/architect.md: had drifted — regenerated by this sync (backend: claude_code)"
    ]

    on_disk = _on_disk_frontmatter(svc, role)
    assert on_disk["title"] == "Ada Lovelace"

    reloaded = await svc.get(role.id)
    assert reloaded.title == "Ada Lovelace"
    assert await _list_title(svc, role.id) == "Ada Lovelace"
    assert "Ada Lovelace" in _claude_md(project)


async def test_dev_role_declared_full_name_reaches_title_on_every_surface(project, svc):
    dev = await svc.add_dev("python")
    _place_override(project.squad_dir, "python-dev", 'full_name = "Grace Hopper"\n')

    skipped = await svc.sync()
    assert skipped == [
        ".claude/agents/python-dev.md: had drifted — regenerated by this sync "
        "(backend: claude_code)"
    ]

    on_disk = _on_disk_frontmatter(svc, dev)
    assert on_disk["title"] == "Grace Hopper"

    reloaded = await svc.get(dev.id)
    assert reloaded.title == "Grace Hopper"
    assert await _list_title(svc, dev.id) == "Grace Hopper"
    assert "Grace Hopper" in _claude_md(project)


# --------------------------------------------------------------------------------------------
# Pair 2: mission -> description, bundled role.
# --------------------------------------------------------------------------------------------


async def test_bundled_role_declared_mission_reaches_description_and_the_mission_definition(
    project, svc
):
    role = await svc.activate_role("architect")
    _place_override(project.squad_dir, "architect", 'mission = "Secure the whole system."\n')

    skipped = await svc.sync()
    assert not skipped

    on_disk = _on_disk_frontmatter(svc, role)
    assert on_disk["description"] == "Secure the whole system."

    reloaded = await svc.get(role.id)
    assert reloaded.description == "Secure the whole system."

    definition = await svc.read_body(reloaded.id)
    assert "Secure the whole system." in definition
    assert _BUNDLED_ARCHITECT.mission not in definition


async def test_dev_role_declared_mission_reaches_description_and_the_mission_definition(
    project, svc
):
    dev = await svc.add_dev("python")
    _place_override(project.squad_dir, "python-dev", 'mission = "Own the whole backend."\n')

    skipped = await svc.sync()
    assert not skipped

    reloaded = await svc.get(dev.id)
    assert reloaded.description == "Own the whole backend."

    definition = await svc.read_body(reloaded.id)
    assert "Own the whole backend." in definition


# --------------------------------------------------------------------------------------------
# The `description` (RoleDef's Claude-pointer one-liner) reaches the pointer, both role kinds.
# --------------------------------------------------------------------------------------------


async def test_bundled_role_declared_description_reaches_the_generated_pointer(project, svc):
    await svc.activate_role("architect")
    _place_override(project.squad_dir, "architect", 'description = "Draws the system diagrams."\n')

    skipped = await svc.sync()
    assert skipped == [
        ".claude/agents/architect.md: had drifted — regenerated by this sync (backend: claude_code)"
    ]

    assert "Draws the system diagrams." in _pointer_text(project, "architect")


async def test_dev_role_declared_description_reaches_the_generated_pointer(project, svc):
    await svc.add_dev("python")
    _place_override(project.squad_dir, "python-dev", 'description = "Ships the Python stack."\n')

    skipped = await svc.sync()
    assert skipped == [
        ".claude/agents/python-dev.md: had drifted — regenerated by this sync "
        "(backend: claude_code)"
    ]

    assert "Ships the Python stack." in _pointer_text(project, "python-dev")


# --------------------------------------------------------------------------------------------
# No declaration leaves fields byte-identical; a value equal to the current one is a no-op.
# --------------------------------------------------------------------------------------------


async def test_an_override_declaring_neither_field_leaves_title_and_description_untouched(
    project, svc
):
    role = await svc.activate_role("architect")
    before = await svc.get(role.id)
    _place_override(project.squad_dir, "architect", 'model = "opus"\n')

    skipped = await svc.sync()
    assert not skipped

    after = await svc.get(role.id)
    assert after.title == before.title
    assert after.description == before.description


async def test_a_declared_full_name_equal_to_the_current_value_takes_the_no_op_path(
    project, svc, monkeypatch
):
    role = await svc.activate_role("architect")
    current_title = role.title
    _place_override(project.squad_dir, "architect", f'full_name = "{current_title}"\n')

    calls: list[str] = []
    real = itemfile.update_frontmatter

    async def _spy(path, item, base, *, default_kind):
        calls.append(item.id)
        return await real(path, item, base, default_kind=default_kind)

    monkeypatch.setattr(maintenance, "update_frontmatter", _spy)

    skipped = await svc.sync()
    assert not skipped
    assert role.id not in calls


# --------------------------------------------------------------------------------------------
# The projection must never route through the title-rename path.
# --------------------------------------------------------------------------------------------


async def test_the_items_path_is_unchanged_across_a_full_name_rename(project, svc):
    role = await svc.activate_role("architect")
    original_path = role.path
    assert "architect" in Path(role.path).name  # the role slug, stamped into the filename

    _place_override(project.squad_dir, "architect", 'full_name = "Ada Lovelace"\n')
    await svc.sync()

    reloaded = await svc.get(role.id)
    assert reloaded.path == original_path
    assert (project.squad_dir / original_path).is_file()
    assert reloaded.slug == "architect"


# --------------------------------------------------------------------------------------------
# File shapes: a second developer's title, and a retired role's record.
# --------------------------------------------------------------------------------------------


async def test_the_second_developers_override_never_touches_the_first_developers_title(
    project, svc
):
    first = await svc.add_dev("python")
    second = await svc.add_dev("typescript")
    _place_override(project.squad_dir, "typescript-dev", 'full_name = "Zara Typescript"\n')

    await svc.sync()

    reloaded_first = await svc.get(first.id)
    reloaded_second = await svc.get(second.id)
    assert reloaded_first.title == first.title
    assert reloaded_second.title == "Zara Typescript"


async def test_an_override_on_a_retired_role_still_reconciles_the_items_own_record(project, svc):
    role = await svc.activate_role("architect")
    await svc.set_status(role.id, "Archived")
    _place_override(project.squad_dir, "architect", 'full_name = "Ada Lovelace"\n')

    skipped = await svc.sync()
    assert not skipped

    reloaded = await svc.get(role.id)
    assert reloaded.title == "Ada Lovelace"
    assert reloaded.status == "Archived"
    assert not (project.root / ".claude" / "agents" / "architect.md").is_file()


# --------------------------------------------------------------------------------------------
# A pre-split corpus converges on the next sync, no migration and no manual step.
# --------------------------------------------------------------------------------------------


async def test_a_pre_split_corpus_converges_on_the_next_sync(project, svc):
    role = await svc.activate_role("architect")
    _place_override(
        project.squad_dir,
        "architect",
        'full_name = "Ada Lovelace"\nmission = "Secure the whole system."\n',
    )

    from squads._index._resolver import item_file
    from squads._itemfile import update_frontmatter

    current = await svc.get(role.id)
    base = current.model_copy(deep=True)
    stale = current.model_copy(deep=True)
    stale.extra[X.FULL_NAME] = "Ada Lovelace"
    stale.extra[X.MISSION] = "Secure the whole system."
    async with svc.store.transaction() as db:
        await update_frontmatter(
            item_file(svc.paths, stale), stale, base, default_kind=svc.spec.default_ref_kind()
        )
        db.add(stale)

    split = await svc.get(role.id)
    assert split.title == _BUNDLED_ARCHITECT.full_name
    assert split.extra[X.FULL_NAME] == "Ada Lovelace"

    skipped = await svc.sync()
    assert skipped == [
        ".claude/agents/architect.md: had drifted — regenerated by this sync (backend: claude_code)"
    ]

    healed = await svc.get(role.id)
    assert healed.title == "Ada Lovelace"
    assert healed.description == "Secure the whole system."


# --------------------------------------------------------------------------------------------
# Rollback: a simulated write failure must leave both the top-level fields and `extra`
# truthful to disk.
# --------------------------------------------------------------------------------------------


async def test_a_simulated_write_failure_leaves_the_item_truthful_to_disk_on_title_too(
    project, svc, monkeypatch
):
    role = await svc.activate_role("architect")
    original_title = role.title
    original_description = role.description
    _place_override(project.squad_dir, "architect", 'full_name = "Ada Lovelace"\n')

    real = itemfile.update_frontmatter

    async def _boom(path, item, base, *, default_kind):
        if item.id == role.id:
            raise SquadsError("simulated write failure")
        return await real(path, item, base, default_kind=default_kind)

    monkeypatch.setattr(maintenance, "update_frontmatter", _boom)

    skipped = await svc.sync()
    assert skipped == [
        "simulated write failure",
        ".claude/agents/architect.md: had drifted — regenerated by this sync "
        "(backend: claude_code)",
    ]

    on_disk = _on_disk_frontmatter(svc, role)
    assert on_disk["title"] == original_title
    reloaded = await svc.get(role.id)
    assert reloaded.title == original_title
    assert reloaded.description == original_description

    assert "Ada Lovelace" in _pointer_text(project, "architect")


async def test_a_raised_write_rolls_back_in_memory_and_a_retry_from_a_clean_state_succeeds(
    project, svc, monkeypatch
):
    """A write that raises leaves ``item`` rolled back in memory to what disk still holds, so
    a clean retry from that same state simply succeeds."""
    role = await svc.activate_role("architect")
    _place_override(project.squad_dir, "architect", 'full_name = "Ada Lovelace"\n')

    real = itemfile.update_frontmatter
    call_count = 0

    async def _boom_once(path, item, base, *, default_kind):
        nonlocal call_count
        if item.id == role.id and call_count == 0:
            call_count += 1
            raise SquadsError("simulated write failure")
        return await real(path, item, base, default_kind=default_kind)

    monkeypatch.setattr(maintenance, "update_frontmatter", _boom_once)
    first_sync = await svc.sync()
    assert first_sync == [
        "simulated write failure",
        ".claude/agents/architect.md: had drifted — regenerated by this sync "
        "(backend: claude_code)",
    ]
    assert "Ada Lovelace" in _pointer_text(project, "architect")

    second_sync = await svc.sync()
    assert second_sync == []
    healed = await svc.get(role.id)
    assert healed.title == "Ada Lovelace"


async def test_an_interrupted_index_commit_is_healed_by_repair_then_a_further_sync_is_silent(
    project, svc
):
    """An interrupted write that landed on disk but never committed to the index is healed by
    ``sq repair``, then a further sync is silent."""
    role = await svc.activate_role("architect")
    original_title = role.title
    original_description = role.description
    _place_override(
        project.squad_dir,
        "architect",
        'full_name = "Ada Lovelace"\nmission = "Secure the whole system."\n',
    )
    first_sync = await svc.sync()
    assert first_sync == [
        ".claude/agents/architect.md: had drifted — regenerated by this sync (backend: claude_code)"
    ]
    applied = await svc.get(role.id)
    assert applied.title == "Ada Lovelace"

    async with svc.store.transaction() as db:
        stale = db.get(role.id)
        assert stale is not None
        stale.title = original_title
        stale.description = original_description
        db.add(stale)

    on_disk_before = _on_disk_frontmatter(svc, role)
    assert on_disk_before["title"] == "Ada Lovelace"
    reloaded_before = await svc.get(role.id)
    assert reloaded_before.title == original_title

    second_sync = await svc.sync()
    matching = [msg for msg in second_sync if role.id in msg]
    assert len(matching) == 1, second_sync
    assert "title" in matching[0] and "description" in matching[0]
    assert "sq repair" in matching[0]
    assert second_sync == matching

    still_on_disk = _on_disk_frontmatter(svc, role)
    assert still_on_disk["title"] == "Ada Lovelace"
    still_index = await svc.get(role.id)
    assert still_index.title == original_title
    assert "Ada Lovelace" in _pointer_text(project, "architect")

    await svc.repair()
    healed = await svc.get(role.id)
    assert healed.title == "Ada Lovelace"
    assert healed.description == "Secure the whole system."

    third_sync = await svc.sync()
    assert third_sync == []


async def test_a_second_genuinely_different_message_about_the_same_item_still_gets_through(
    project, svc
):
    """The dedup collapses only exact-text duplicates: a second, textually different report
    about the same item must not be swallowed alongside a real frontmatter skew."""
    from squads._index._resolver import item_file
    from squads._sections import replace_frontmatter

    unrenderable_model = "claude-opus-4-5"
    dev = await svc.add_dev("python", model=unrenderable_model)

    db = await svc.store.load()
    indexed = db.get(dev.id)
    assert indexed is not None
    indexed.extra.pop("responsibilities", None)
    await svc.store.overwrite(db)

    path = item_file(svc.paths, dev)
    text = path.read_text(encoding="utf-8")
    mutated = dev.model_copy(deep=True)
    mutated.extra.pop("responsibilities", None)
    mutated.title = "A Disk-Only Title Nobody Told The Index About"
    path.write_text(
        replace_frontmatter(text, mutated.to_frontmatter_dict(), source=str(path)),
        encoding="utf-8",
    )

    skipped = await svc.sync()
    skew_lines = [msg for msg in skipped if dev.id in msg and "diverged" in msg]
    model_lines = [msg for msg in skipped if unrenderable_model in msg]
    assert len(skew_lines) == 1, skipped
    assert len(model_lines) == 1, skipped
    assert skew_lines[0] != model_lines[0]

    on_disk = _on_disk_frontmatter(svc, dev)
    assert on_disk["title"] == "A Disk-Only Title Nobody Told The Index About"


# --------------------------------------------------------------------------------------------
# sq check's pointer-currency rule catches a generated pointer that no longer matches what it
# should currently render, until the sync that regenerates it.
# --------------------------------------------------------------------------------------------


async def test_sq_check_reports_the_pointer_as_drifted_until_the_sync_that_regenerates_it(
    project, svc
):
    role = await svc.activate_role("architect")
    _place_override(project.squad_dir, "architect", 'full_name = "Ada Lovelace"\n')

    before_issues = await svc.check()
    assert len(before_issues) == 1
    assert before_issues[0].item == ".claude/agents/architect.md"
    assert "drifted" in before_issues[0].message

    await svc.sync()

    after_issues = await svc.check()
    assert not after_issues

    reloaded = await svc.get(role.id)
    assert reloaded.title == "Ada Lovelace"


async def test_repair_is_a_stable_no_op_after_a_full_name_projection(project, svc):
    role = await svc.activate_role("architect")
    _place_override(project.squad_dir, "architect", 'full_name = "Ada Lovelace"\n')
    await svc.sync()

    result = await svc.repair()
    assert result.missing_ids == []
    assert result.unreadable == []

    reloaded = await svc.get(role.id)
    assert reloaded.title == "Ada Lovelace"
