"""A role override's resolved ``full_name``/``mission`` reaches the item's own top-level
``title``/``description`` — not only their ``extra`` mirror — via the projection table
declared on ``RoleDef`` (``title`` from ``full_name``, ``description`` from ``mission``) and
looped by ``_refresh_catalog_extra``.

Every assertion here checks the *declared string* itself, never agreement between the
top-level field and its ``extra`` copy — a projection that writes the stale bundled value into
both would pass an agreement-only check and prove nothing.
"""

from pathlib import Path

import pytest

from squads import __version__
from squads import _itemfile as itemfile
from squads._errors import SquadsError
from squads._models._extras import ExtraKey as X
from squads._roles._catalog import PREDEFINED
from squads._roles._resolver import resolve_role_for_item
from squads._services import _maintenance as maintenance
from squads._workflow import ROSTER_ROLE

pytestmark = pytest.mark.anyio

_BUNDLED_ARCHITECT = next(r for r in PREDEFINED if r.slug == "architect")


def _place_override(squad_dir: Path, slug: str, content: str) -> None:
    """Write a stamped ``.overrides/roles/<slug>.toml`` — the stamp matters here because
    ``sq check`` warns on an unstamped override, and several tests below assert a clean
    ``sq check`` around the sync that applies the projection."""
    target = squad_dir / ".overrides" / "roles" / f"{slug}.toml"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(f"# squads:override-base:{__version__}\n{content}", encoding="utf-8")


def _on_disk_frontmatter(svc, item) -> dict[str, object]:
    from squads._index._resolver import item_file

    return itemfile.read_frontmatter(text=item_file(svc.paths, item).read_text(encoding="utf-8"))


def _claude_md(project) -> str:
    return (project.root / "CLAUDE.md").read_text(encoding="utf-8")


def _pointer_text(project, slug: str) -> str:
    return (project.root / ".claude" / "agents" / f"{slug}.md").read_text(encoding="utf-8")


async def _list_title(svc, item_id: str) -> str:
    items = await svc.list_items(item_type=ROSTER_ROLE)
    return next(it.title for it in items if it.id == item_id)


# --------------------------------------------------------------------------------------------
# Pair 1: full_name -> title, bundled role.
# --------------------------------------------------------------------------------------------


async def test_bundled_role_declared_full_name_reaches_title_on_every_surface(project, svc):
    role = await svc.activate_role("architect")
    _place_override(project.squad_dir, "architect", 'full_name = "Ada Lovelace"\n')

    skipped = await svc.sync()
    # The override renamed the role after the pointer was already written under the bundled
    # name — this sync is what first regenerates it, a genuine currency fix.
    assert skipped == [
        ".claude/agents/architect.md: had drifted — regenerated by this sync (backend: claude_code)"
    ]

    on_disk = _on_disk_frontmatter(svc, role)
    assert on_disk["title"] == "Ada Lovelace"  # declared string, not "agrees with extra"

    reloaded = await svc.get(role.id)
    assert reloaded.title == "Ada Lovelace"
    assert await _list_title(svc, role.id) == "Ada Lovelace"  # `sq list -t role`
    assert "Ada Lovelace" in _claude_md(project)  # compiled roster line


async def test_dev_role_declared_full_name_reaches_title_on_every_surface(project, svc):
    dev = await svc.add_dev("python")
    _place_override(project.squad_dir, "python-dev", 'full_name = "Grace Hopper"\n')

    skipped = await svc.sync()
    # Same currency fix as the bundled-role pair above, on the dev pointer.
    assert skipped == [
        ".claude/agents/python-dev.md: had drifted — regenerated by this sync "
        "(backend: claude_code)"
    ]

    on_disk = _on_disk_frontmatter(svc, dev)
    assert on_disk["title"] == "Grace Hopper"

    reloaded = await svc.get(dev.id)
    assert reloaded.title == "Grace Hopper"
    assert await _list_title(svc, dev.id) == "Grace Hopper"
    assert "Grace Hopper" in _claude_md(project)


# --------------------------------------------------------------------------------------------
# Pair 2: mission -> description, bundled role. Covers the card AND the `## Mission`
# definition text — resolved fresh at read time, not read back from any stored body.
# --------------------------------------------------------------------------------------------


async def test_bundled_role_declared_mission_reaches_description_and_the_mission_definition(
    project, svc
):
    role = await svc.activate_role("architect")
    _place_override(project.squad_dir, "architect", 'mission = "Secure the whole system."\n')

    skipped = await svc.sync()
    assert not skipped

    on_disk = _on_disk_frontmatter(svc, role)
    assert on_disk["description"] == "Secure the whole system."

    reloaded = await svc.get(role.id)
    assert reloaded.description == "Secure the whole system."

    definition = svc.role_definition_text(resolve_role_for_item(reloaded, svc.paths.squad_dir))
    assert "Secure the whole system." in definition
    assert _BUNDLED_ARCHITECT.mission not in definition  # the stale bundled mission is gone


async def test_dev_role_declared_mission_reaches_description_and_the_mission_definition(
    project, svc
):
    dev = await svc.add_dev("python")
    _place_override(project.squad_dir, "python-dev", 'mission = "Own the whole backend."\n')

    skipped = await svc.sync()
    assert not skipped

    reloaded = await svc.get(dev.id)
    assert reloaded.description == "Own the whole backend."

    definition = svc.role_definition_text(resolve_role_for_item(reloaded, svc.paths.squad_dir))
    assert "Own the whole backend." in definition


# --------------------------------------------------------------------------------------------
# The dropped `description` (RoleDef's Claude-pointer one-liner) now reaches the pointer, for
# both role kinds -- landed as a reconciled-but-non-exempt key (see the PERMITTED_EXTRA_SKEW
# tests) rather than a member of `_EXTRA_FIELD_KEYS`.
# --------------------------------------------------------------------------------------------


async def test_bundled_role_declared_description_reaches_the_generated_pointer(project, svc):
    await svc.activate_role("architect")
    _place_override(project.squad_dir, "architect", 'description = "Draws the system diagrams."\n')

    skipped = await svc.sync()
    # The override changed the pointer's own frontmatter `description` after it was already
    # written under the bundled one — a genuine currency fix.
    assert skipped == [
        ".claude/agents/architect.md: had drifted — regenerated by this sync (backend: claude_code)"
    ]

    assert "Draws the system diagrams." in _pointer_text(project, "architect")


async def test_dev_role_declared_description_reaches_the_generated_pointer(project, svc):
    await svc.add_dev("python")
    _place_override(project.squad_dir, "python-dev", 'description = "Ships the Python stack."\n')

    skipped = await svc.sync()
    assert skipped == [
        ".claude/agents/python-dev.md: had drifted — regenerated by this sync "
        "(backend: claude_code)"
    ]

    assert "Ships the Python stack." in _pointer_text(project, "python-dev")


# --------------------------------------------------------------------------------------------
# The `if not previous` gate: no declaration -> byte-identical fields; a value equal to the
# current one -> the same no-op path (asserted directly, not assumed).
# --------------------------------------------------------------------------------------------


async def test_an_override_declaring_neither_field_leaves_title_and_description_untouched(
    project, svc
):
    role = await svc.activate_role("architect")
    before = await svc.get(role.id)
    _place_override(project.squad_dir, "architect", 'model = "opus"\n')

    skipped = await svc.sync()
    assert not skipped

    after = await svc.get(role.id)
    assert after.title == before.title
    assert after.description == before.description


async def test_a_declared_full_name_equal_to_the_current_value_takes_the_no_op_path(
    project, svc, monkeypatch
):
    role = await svc.activate_role("architect")
    current_title = role.title
    _place_override(project.squad_dir, "architect", f'full_name = "{current_title}"\n')

    calls: list[str] = []
    real = maintenance.update_frontmatter

    async def _spy(path, item, base, *, default_kind):
        calls.append(item.id)
        return await real(path, item, base, default_kind=default_kind)

    monkeypatch.setattr(maintenance, "update_frontmatter", _spy)

    skipped = await svc.sync()
    assert not skipped
    assert role.id not in calls  # no write at all -- the true no-op path, not a same-value write


# --------------------------------------------------------------------------------------------
# The data-loss hazard: the projection must never route through the title-rename path, so the
# item's own path (its role-slug filename) is unchanged across a full_name rename.
# --------------------------------------------------------------------------------------------


async def test_the_items_path_is_unchanged_across_a_full_name_rename(project, svc):
    role = await svc.activate_role("architect")
    original_path = role.path
    assert "architect" in Path(role.path).name  # the role slug, stamped into the filename

    _place_override(project.squad_dir, "architect", 'full_name = "Ada Lovelace"\n')
    await svc.sync()

    reloaded = await svc.get(role.id)
    assert reloaded.path == original_path
    assert (project.squad_dir / original_path).is_file()
    assert reloaded.slug == "architect"  # the role slug, never a slug of the new title


# --------------------------------------------------------------------------------------------
# File shapes: a second developer's title must be untouched by the first's override; an
# override on a retired role still reconciles the item's own record even though its backend
# projection stays withdrawn.
# --------------------------------------------------------------------------------------------


async def test_the_second_developers_override_never_touches_the_first_developers_title(
    project, svc
):
    first = await svc.add_dev("python")
    second = await svc.add_dev("typescript")
    _place_override(project.squad_dir, "typescript-dev", 'full_name = "Zara Typescript"\n')

    await svc.sync()

    reloaded_first = await svc.get(first.id)
    reloaded_second = await svc.get(second.id)
    assert reloaded_first.title == first.title  # untouched
    assert reloaded_second.title == "Zara Typescript"


async def test_an_override_on_a_retired_role_still_reconciles_the_items_own_record(project, svc):
    role = await svc.activate_role("architect")
    await svc.set_status(role.id, "Archived")
    _place_override(project.squad_dir, "architect", 'full_name = "Ada Lovelace"\n')

    skipped = await svc.sync()
    assert not skipped

    reloaded = await svc.get(role.id)
    assert reloaded.title == "Ada Lovelace"
    assert reloaded.status == "Archived"  # the transition itself is untouched by this call
    # withdrawn: no live pointer materialised for a retired role
    assert not (project.root / ".claude" / "agents" / "architect.md").is_file()


# --------------------------------------------------------------------------------------------
# A pre-split corpus -- an item already carrying a stale title/description from before this
# projection existed -- converges on the next sync, no migration and no manual step.
# --------------------------------------------------------------------------------------------


async def test_a_pre_split_corpus_converges_on_the_next_sync(project, svc):
    role = await svc.activate_role("architect")
    _place_override(
        project.squad_dir,
        "architect",
        'full_name = "Ada Lovelace"\nmission = "Secure the whole system."\n',
    )

    # Simulate the split this task fixes: extra already carries the declared values (an older
    # release's writer merged only `to_extra()`), but the item's own top-level fields still
    # hold what `create` stamped at activation.
    from squads._index._resolver import item_file
    from squads._itemfile import update_frontmatter

    current = await svc.get(role.id)
    base = current.model_copy(deep=True)
    stale = current.model_copy(deep=True)
    stale.extra[X.FULL_NAME] = "Ada Lovelace"
    stale.extra[X.MISSION] = "Secure the whole system."
    async with svc.store.transaction() as db:
        await update_frontmatter(
            item_file(svc.paths, stale), stale, base, default_kind=svc.spec.default_ref_kind()
        )
        db.add(stale)

    split = await svc.get(role.id)
    assert split.title == _BUNDLED_ARCHITECT.full_name  # still stale
    assert split.extra[X.FULL_NAME] == "Ada Lovelace"  # already correct

    skipped = await svc.sync()
    # The pointer was written at activation under the bundled name, before the override (and
    # this simulated split) ever applied — this sync is the first to reflect "Ada Lovelace".
    assert skipped == [
        ".claude/agents/architect.md: had drifted — regenerated by this sync (backend: claude_code)"
    ]

    healed = await svc.get(role.id)
    assert healed.title == "Ada Lovelace"
    assert healed.description == "Secure the whole system."


# --------------------------------------------------------------------------------------------
# Rollback: a simulated write failure must leave BOTH the top-level fields and `extra` truthful
# to disk -- the property the `extra`-shaped rollback already held, now extended to `title`/
# `description`. Observed downstream, in the same sync pass, through the generated pointer --
# proving the in-memory item used by later steps was actually rolled back, not just
# theoretically restorable.
# --------------------------------------------------------------------------------------------


async def test_a_simulated_write_failure_leaves_the_item_truthful_to_disk_on_title_too(
    project, svc, monkeypatch
):
    role = await svc.activate_role("architect")
    original_title = role.title
    original_description = role.description
    _place_override(project.squad_dir, "architect", 'full_name = "Ada Lovelace"\n')

    real = maintenance.update_frontmatter

    async def _boom(path, item, base, *, default_kind):
        if item.id == role.id:
            raise SquadsError("simulated write failure")
        return await real(path, item, base, default_kind=default_kind)

    monkeypatch.setattr(maintenance, "update_frontmatter", _boom)

    skipped = await svc.sync()
    # The write failure is reported, and the pointer regen in the same pass is now a second,
    # genuinely different report: it resolves the role through the override directly (not
    # through the item's own -- unmerged -- mirror), so it finds the override and regenerates
    # a currently-wrong pointer regardless of whether the merge that would have committed the
    # override into the item's own record succeeded.
    assert skipped == [
        "simulated write failure",
        ".claude/agents/architect.md: had drifted — regenerated by this sync "
        "(backend: claude_code)",
    ]

    # Nothing committed to the item's own record: disk and index both still hold the
    # original title -- the failed merge did not corrupt the in-memory item.
    on_disk = _on_disk_frontmatter(svc, role)
    assert on_disk["title"] == original_title
    reloaded = await svc.get(role.id)
    assert reloaded.title == original_title
    assert reloaded.description == original_description

    # The pointer, unlike the item's own record, is already current -- it never depended on
    # this merge succeeding at all.
    assert "Ada Lovelace" in _pointer_text(project, "architect")


async def test_a_raised_write_rolls_back_in_memory_and_a_retry_from_a_clean_state_succeeds(
    project, svc, monkeypatch
):
    """Renamed from ``test_repair_and_a_further_sync_are_unaffected_by_the_interrupted_role_
    write``: that name promised the markdown-written / index-commit-not-reached shape, but
    patching the whole ``update_frontmatter`` function means its own last statement — the
    ``_aio.atomic_write_text`` call — is never reached, so nothing lands on either side. What
    this actually falsifies, and still must: a write that raises leaves ``item`` rolled back
    in memory to what disk still holds (not the attempted value), so a clean retry from that
    same, untouched state simply succeeds. The shape the old name promised — markdown ahead,
    index commit not reached, then ``svc.repair()`` and a further sync — gets its own test
    below, ``test_an_interrupted_index_commit_is_healed_by_repair_then_a_further_sync_is_
    silent``.
    """
    role = await svc.activate_role("architect")
    _place_override(project.squad_dir, "architect", 'full_name = "Ada Lovelace"\n')

    real = maintenance.update_frontmatter
    call_count = 0

    async def _boom_once(path, item, base, *, default_kind):
        nonlocal call_count
        if item.id == role.id and call_count == 0:
            call_count += 1
            raise SquadsError("simulated write failure")
        return await real(path, item, base, default_kind=default_kind)

    monkeypatch.setattr(maintenance, "update_frontmatter", _boom_once)
    first_sync = await svc.sync()
    # The failed write rolls the item back to what disk still held (the bundled name) --
    # but the pointer regen in the SAME pass resolves the role through the override directly,
    # not through the item's own (unmerged) mirror, so it already moves the pointer to "Ada
    # Lovelace" here, before the item's own record has caught up at all.
    assert first_sync == [
        "simulated write failure",
        ".claude/agents/architect.md: had drifted — regenerated by this sync "
        "(backend: claude_code)",
    ]
    assert "Ada Lovelace" in _pointer_text(project, "architect")

    second_sync = await svc.sync()
    # This retry succeeds, committing the item's own record to "Ada Lovelace" too -- the
    # pointer was already current, so this pass finds nothing left to regenerate.
    assert second_sync == []
    healed = await svc.get(role.id)
    assert healed.title == "Ada Lovelace"


async def test_an_interrupted_index_commit_is_healed_by_repair_then_a_further_sync_is_silent(
    project, svc
):
    """The shape a real interrupted role-projection write actually takes: the ``.md`` file is
    ahead of the index (an interrupted write that landed on disk but whose index commit never
    happened — the sanctioned one-sided skew invariant 8 describes), not "nothing written on
    either side".

    Simulated directly — roll the index back on the role's own projected
    ``title``/``description`` to what it held before the override applied, leaving the ``.md``
    file exactly as the earlier, real sync left it.
    """
    role = await svc.activate_role("architect")
    original_title = role.title
    original_description = role.description
    _place_override(
        project.squad_dir,
        "architect",
        'full_name = "Ada Lovelace"\nmission = "Secure the whole system."\n',
    )
    first_sync = await svc.sync()
    # The override renamed the role after the pointer was already written under the bundled
    # name — this sync is what first regenerates it, a genuine currency fix.
    assert first_sync == [
        ".claude/agents/architect.md: had drifted — regenerated by this sync (backend: claude_code)"
    ]
    applied = await svc.get(role.id)
    assert applied.title == "Ada Lovelace"

    # Roll the index back to the pre-override state -- INDEX ONLY, the `.md` file is
    # untouched (still "Ada Lovelace" / "Secure the whole system.").
    async with svc.store.transaction() as db:
        stale = db.get(role.id)
        assert stale is not None
        stale.title = original_title
        stale.description = original_description
        db.add(stale)

    on_disk_before = _on_disk_frontmatter(svc, role)
    assert on_disk_before["title"] == "Ada Lovelace"  # disk still ahead
    reloaded_before = await svc.get(role.id)
    assert reloaded_before.title == original_title  # index rolled back

    # Deliverable 1 evidence: one divergence on one item, one warning -- counted, not
    # substring-matched, so a silent regression to "two lines again" would redden this.
    second_sync = await svc.sync()
    matching = [msg for msg in second_sync if role.id in msg]
    assert len(matching) == 1, second_sync
    assert "title" in matching[0] and "description" in matching[0]
    assert "sq repair" in matching[0]
    # The gap this used to surface is gone: the skip above leaves `item` at the stale
    # (rolled-back) index values, but the pointer regen in the SAME pass resolves the role
    # through the override directly rather than through that stale item, so it is unaffected
    # by the rollback and finds nothing to regenerate -- the skew warning above is the only
    # report this sync produces.
    assert second_sync == matching

    # Frontmatter, the index, AND the pointer are exactly as before this sync -- nothing moved.
    still_on_disk = _on_disk_frontmatter(svc, role)
    assert still_on_disk["title"] == "Ada Lovelace"
    still_index = await svc.get(role.id)
    assert still_index.title == original_title
    assert "Ada Lovelace" in _pointer_text(project, "architect")

    await svc.repair()
    healed = await svc.get(role.id)
    assert healed.title == "Ada Lovelace"
    assert healed.description == "Secure the whole system."

    third_sync = await svc.sync()
    # The pointer never regressed, so there is nothing left for a further sync to fix.
    assert third_sync == []


async def test_a_second_genuinely_different_message_about_the_same_item_still_gets_through(
    project, svc
):
    """The dedup collapses only exact-text duplicates -- a second, textually different report
    about the *same* item (here: an unrenderable ``model`` the backend drops, reported on
    every sync by :meth:`_project_roster_item` regardless of any skew, alongside a real
    frontmatter skew :meth:`_refresh_catalog_extra` catches while merging a stale catalog
    field, both on one dev role in one sync) must not be swallowed alongside it.

    ``_refresh_catalog_extra`` only reaches ``update_frontmatter`` (and so
    ``ensure_no_skew``) when its own merge actually finds something to change -- a bare dev
    role fresh off ``add_dev`` never diverges from its own catalog base, so it could never
    surface a manufactured disk-only skew this way. Stripping ``responsibilities`` from the
    index (consistently, off disk too, so it is not itself reported as skew) gives the merge
    something real to restore -- the dev-role template regenerates it fresh every call -- so
    the writer runs at all. A role override is deliberately not used for this instead: it
    would validate the *merged* (base + override) ``model``, and this role's own stored model
    is the unrenderable one under test.
    """
    from squads._index._resolver import item_file
    from squads._itemfile import replace_frontmatter

    unrenderable_model = "claude-opus-4-5"
    dev = await svc.add_dev("python", model=unrenderable_model)

    # Strip a dev-template-derived field from the index only the merge would otherwise agree
    # with disk about -- dropped from disk too below, so it is never itself reported as a
    # divergence; only the manufactured title is.
    db = await svc.store.load()
    indexed = db.get(dev.id)
    assert indexed is not None
    indexed.extra.pop("responsibilities", None)
    await svc.store.overwrite(db)

    path = item_file(svc.paths, dev)
    text = path.read_text(encoding="utf-8")
    mutated = dev.model_copy(deep=True)
    mutated.extra.pop("responsibilities", None)
    mutated.title = "A Disk-Only Title Nobody Told The Index About"
    path.write_text(
        replace_frontmatter(text, mutated.to_frontmatter_dict(), source=str(path)),
        encoding="utf-8",
    )

    skipped = await svc.sync()
    skew_lines = [msg for msg in skipped if dev.id in msg and "diverged" in msg]
    model_lines = [msg for msg in skipped if unrenderable_model in msg]
    assert len(skew_lines) == 1, skipped
    assert len(model_lines) == 1, skipped
    assert skew_lines[0] != model_lines[0]

    # And the write really was refused, not silently overwritten -- the disk-only title
    # this test manufactured still stands.
    on_disk = _on_disk_frontmatter(svc, dev)
    assert on_disk["title"] == "A Disk-Only Title Nobody Told The Index About"


# --------------------------------------------------------------------------------------------
# sq check's pointer-currency rule is not a new rule -- it already existed to catch exactly
# this shape (a generated pointer that no longer matches what it should currently render).
# Its expectation now resolves through the override directly rather than through the item's
# own not-yet-synced mirror, so it can finally reach the gap between "the override exists" and
# "a sync has projected it onto the item" that a mirror-backed expectation could never see:
# the pointer is genuinely stale here (still the bundled name activation wrote), and the rule
# now says so. After the sync that regenerates it, the same rule reports it current again.
# --------------------------------------------------------------------------------------------


async def test_sq_check_reports_the_pointer_as_drifted_until_the_sync_that_regenerates_it(
    project, svc
):
    role = await svc.activate_role("architect")
    _place_override(project.squad_dir, "architect", 'full_name = "Ada Lovelace"\n')

    # The override exists, but nothing has projected it onto the pointer yet -- a genuine
    # currency gap, and the resolved expectation now sees it.
    before_issues = await svc.check()
    assert len(before_issues) == 1
    assert before_issues[0].item == ".claude/agents/architect.md"
    assert "drifted" in before_issues[0].message

    await svc.sync()

    after_issues = await svc.check()
    assert not after_issues

    reloaded = await svc.get(role.id)
    assert reloaded.title == "Ada Lovelace"


async def test_repair_is_a_stable_no_op_after_a_full_name_projection(project, svc):
    role = await svc.activate_role("architect")
    _place_override(project.squad_dir, "architect", 'full_name = "Ada Lovelace"\n')
    await svc.sync()

    result = await svc.repair()
    assert result.missing_ids == []
    assert result.unreadable == []

    reloaded = await svc.get(role.id)
    assert reloaded.title == "Ada Lovelace"
