"""``Service.set_body``: replaces the ``:body`` region by default, joins onto the existing
content with a blank-line separator when ``append=True``, and is rejected outright for a
role — its body is generated from its fields, not hand-written. A system (template-owned)
skill is rejected the same way (its body is regenerated by `sq sync`); a custom
(author-defined) skill is the one meta-type exception and accepts an authored body.
"""

import pytest

from squads._errors import SquadsError

pytestmark = pytest.mark.anyio


async def test_set_body_replaces_by_default_and_appends_with_a_blank_line_separator(svc):
    task = (await svc.create("task", "t", description="summary stays in frontmatter")).item

    await svc.set_body(task.id, "## Description\n\nFull body content.")
    assert await svc.read_body(task.id) == "## Description\n\nFull body content."
    # the frontmatter summary is untouched by a body change
    assert (await svc.get(task.id)).description == "summary stays in frontmatter"

    await svc.set_body(task.id, "More detail.", append=True)
    assert (await svc.read_body(task.id)).endswith("Full body content.\n\nMore detail.")


async def test_set_body_on_a_role_is_rejected_as_generated_from_its_fields(svc):
    with pytest.raises(SquadsError, match="generated from its fields"):
        await svc.set_body("ROLE-000001", "free-form body")


async def test_set_body_on_a_system_skill_is_rejected_as_regenerated_by_sync(svc):
    seeded = await svc.seed_bundled_skills()
    with pytest.raises(SquadsError, match="regenerated by `sq sync`"):
        await svc.set_body(seeded[0].id, "free-form body")


async def test_set_body_on_a_custom_skill_is_authored_and_re_editable(svc):
    skill = await svc.add_skill("Release Runbook", description="Ship a release safely.")

    await svc.set_body(skill.id, "## Instructions\n\nCut the branch, then tag.")
    assert await svc.read_body(skill.id) == "## Instructions\n\nCut the branch, then tag."

    await svc.set_body(skill.id, "Then publish.", append=True)
    assert (await svc.read_body(skill.id)).endswith("tag.\n\nThen publish.")
