"""The roles catalog document (``.overrides/roles.toml``) reaching a role that already has a
live roster item — the gap between this document and a per-slug ``.overrides/roles/<slug>.toml``
file: the per-slug layer always applied on the activated path, the catalog document did not,
because ``role_base_from_item`` built its base from the bundled catalog alone.

Driven through ``sq sync``'s catalog refresh (``_refresh_catalog_extra``) and ``sq check``'s
role-override resolve (``_check_role_override_resolves``, via ``check_override_issues``/
``svc.check()``) — the two production callers in this file's own territory. ``sq role <slug>
show`` is exercised at the CLI layer (see
``tests/unit/test_role_base_from_item_dispatches_by_role_kind.py`` for the pure-function proof).

The ``sq check`` proof below needs a value the *document* can set that slips past
``load_role_catalog``'s own catalog-wide validation (which would otherwise refuse it at
document-load time, before activation is even relevant) but that the per-slug merge's
post-merge blank-string refusal still catches — a blank ``color`` is exactly that gap, and
the same technique the pre-existing
``tests/integration/test_blank_role_override_field_breaks_no_generated_surface.py`` already
uses for the per-slug-only case.
"""

from pathlib import Path

import pytest

from squads import __version__
from squads._roles._catalog import PREDEFINED

pytestmark = pytest.mark.anyio


def _resolved(svc, item):
    """*item*'s definition as every reader of it resolves one -- a role's title and mission are
    catalog answers, never copies stored in its ``extra``."""
    from squads._roles._resolver import resolve_role_for_item

    return resolve_role_for_item(item, svc.paths.squad_dir)


_BUNDLED_ARCHITECT = next(r for r in PREDEFINED if r.slug == "architect")


def _write_catalog_document(squad_dir: Path, content: str) -> None:
    """Stamped, so ``sq check``'s shadowing-unstamped-is-an-error rule doesn't fire — the
    stamp obligation is a different task's concern; this file is about the merge reaching an
    activated role."""
    (squad_dir / ".overrides").mkdir(parents=True, exist_ok=True)
    (squad_dir / ".overrides" / "roles.toml").write_text(
        f"# squads:override-base:{__version__}\n{content}", encoding="utf-8"
    )


def _write_slug_override(squad_dir: Path, slug: str, content: str) -> None:
    target = squad_dir / ".overrides" / "roles" / f"{slug}.toml"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")


async def test_a_catalog_document_field_reaches_an_already_activated_role_via_sync(project, svc):
    """One override must apply on both sides of activation: an override that reaches a
    not-yet-activated slug and then silently stops the moment the slug is activated reads as a
    bug. Proven here on the *activated* side."""
    role = await svc.activate_role("architect")
    _write_catalog_document(
        project.squad_dir, '[[roles]]\nslug = "architect"\ntitle = "Chief Architect"\n'
    )

    skipped = await svc.sync()
    # The catalog document changed the resolved title after the pointer was already written
    # with the old one — a genuine currency fix, reported the same way a hand-edit would be.
    assert skipped == [
        ".claude/agents/architect.md: had drifted — regenerated by this sync (backend: claude_code)"
    ]

    reloaded = await svc.get(role.id)
    assert _resolved(svc, reloaded).title == "Chief Architect"
    assert _resolved(svc, reloaded).mission == _BUNDLED_ARCHITECT.mission  # untouched, unaffected


async def test_a_squad_with_no_catalog_document_syncs_exactly_as_before(project, svc):
    role = await svc.activate_role("architect")
    skipped = await svc.sync()
    assert not skipped
    reloaded = await svc.get(role.id)
    assert _resolved(svc, reloaded).title == _BUNDLED_ARCHITECT.title


async def test_precedence_bundled_then_catalog_document_then_per_slug_file(project, svc):
    """All three layers naming the same role: the catalog document's title reaches the
    activated item, and the per-slug file's model still wins over it, per the stated
    precedence order — bundled -> catalog document -> per-slug file."""
    role = await svc.activate_role("architect")
    _write_catalog_document(
        project.squad_dir, '[[roles]]\nslug = "architect"\ntitle = "Chief Architect"\n'
    )
    _write_slug_override(project.squad_dir, "architect", 'model = "haiku"\n')

    await svc.sync()

    reloaded = await svc.get(role.id)
    resolved = _resolved(svc, reloaded)
    assert resolved.title == "Chief Architect"  # catalog document, over bundled
    assert resolved.model == "haiku"  # per-slug file, over the catalog document


async def test_sq_check_stays_clean_with_the_catalog_document_reaching_an_activated_role(
    project, svc
):
    await svc.activate_role("architect")
    _write_catalog_document(
        project.squad_dir, '[[roles]]\nslug = "architect"\ntitle = "Chief Architect"\n'
    )

    await svc.sync()

    assert not await svc.check()


async def test_sq_check_role_override_resolve_now_reads_the_catalog_document(project, svc):
    """The gap this closes: ``_check_role_override_resolves`` built its base from
    ``role_base_from_item(item)`` with no ``squad_dir``, so a per-slug override's merge base
    was always bundled-only even with a catalog document present. A blank ``color`` in the
    document passes ``load_role_catalog``'s own validation (it isn't a required field there)
    but fails the per-slug merge's post-merge blank-string refusal — so this only surfaces
    once the check's base actually incorporates the document."""
    await svc.activate_role("architect")
    _write_catalog_document(project.squad_dir, '[[roles]]\nslug = "architect"\ncolor = ""\n')
    _write_slug_override(
        project.squad_dir,
        "architect",
        f'# squads:override-base:{__version__}\ntitle = "Chief Architect (per-slug)"\n',
    )

    issues = await svc.check()

    matching = [i for i in issues if "architect.toml" in i.item]
    assert len(matching) == 1, issues
    assert matching[0].level == "error"
    assert "color" in matching[0].message
    assert "blank or whitespace-only" in matching[0].message


async def test_sq_check_stays_clean_for_the_same_per_slug_file_with_no_document(project, svc):
    """Isolates the cause: remove the document (keep the same per-slug file) and the
    ``error``-level issue disappears — proving the document's blank ``color`` is what produced
    it, not the per-slug file alone.

    A ``warn`` remains, and is expected: the per-slug override changes the resolved title
    after ``activate_role`` already wrote the pointer under the bundled one, and the pointer
    expectation now resolves through the override directly rather than through the item's own
    not-yet-synced mirror, so it correctly reports that genuine currency gap — not a false
    positive, and not what this test isolates."""
    await svc.activate_role("architect")
    _write_slug_override(
        project.squad_dir,
        "architect",
        f'# squads:override-base:{__version__}\ntitle = "Chief Architect (per-slug)"\n',
    )

    issues = await svc.check()
    assert not [i for i in issues if i.level == "error"]
    assert [i.level for i in issues] == ["warn"]  # only the expected pointer-currency gap


async def test_sq_check_stays_clean_for_a_valid_document_field_reaching_the_same_role(project, svc):
    """The positive case: a *valid* document field change plus a per-slug file overriding a
    different field resolves with no ``error`` through the same check call site (no false
    positive from threading squad_dir in), and the sync path (already proven above) confirms
    both values actually land on the activated item.

    The same expected ``warn`` as the isolation test above rides along here too: neither
    override has been synced onto the pointer yet."""
    role = await svc.activate_role("architect")
    _write_catalog_document(
        project.squad_dir,
        '[[roles]]\nslug = "architect"\nmission = "Own the whole system\'s shape and its '
        'security posture."\n',
    )
    _write_slug_override(
        project.squad_dir,
        "architect",
        f'# squads:override-base:{__version__}\ntitle = "Chief Architect (per-slug)"\n',
    )

    issues = await svc.check()
    assert not [i for i in issues if i.level == "error"]
    assert [i.level for i in issues] == ["warn"]

    await svc.sync()
    assert not await svc.check()  # the warn clears once the sync it names has run
    reloaded = await svc.get(role.id)
    resolved = _resolved(svc, reloaded)
    assert resolved.mission == "Own the whole system's shape and its security posture."
    assert resolved.title == "Chief Architect (per-slug)"
