"""Per-release content-hash manifest for bundled templates.

The manifest is shipped as package data at ``squads._rendering/templates_manifest.json``.
It maps ``squads_version → {template_name → sha256_hex}`` and accumulates across releases,
so ``sq override diff`` can recover the base-version bundled template content even after
an upgrade.

The manifest is generated by ``scripts/gen_template_manifest.py`` before each release.

@devops Wire ``python scripts/gen_template_manifest.py`` into the release pipeline before
``uv build`` so each release ships updated hashes.  The manifest lives in
``src/squads/_rendering/templates_manifest.json`` and ships automatically as package data
(same directory as the bundled templates).
"""

import hashlib
import importlib.resources as pkg_resources
import json

# Cached manifest data: version → {template_name → sha256_hex}.
_manifest_cache: dict[str, dict[str, str]] | None = None


def _load_manifest() -> dict[str, dict[str, str]]:
    """Load and cache the shipped manifest from package data."""
    global _manifest_cache
    if _manifest_cache is not None:
        return _manifest_cache
    ref = pkg_resources.files("squads._rendering") / "templates_manifest.json"
    try:
        raw = ref.read_text(encoding="utf-8")
        data: dict[str, dict[str, str]] = json.loads(raw)
        _manifest_cache = data
    except FileNotFoundError, json.JSONDecodeError:
        _manifest_cache = {}
    return _manifest_cache


def template_hash_at_version(template_name: str, version: str) -> str | None:
    """Return the SHA-256 hex for *template_name* as it was in *version*, or ``None``.

    Returns ``None`` when the version or template are not recorded in the manifest.
    """
    manifest = _load_manifest()
    ver_entry = manifest.get(version)
    if ver_entry is None:
        return None
    return ver_entry.get(template_name)


def current_template_hash(template_name: str) -> str | None:
    """Return the SHA-256 of the currently-installed bundled template, or ``None``."""
    ref = pkg_resources.files("squads._rendering.templates") / template_name
    try:
        raw = ref.read_bytes()
    except FileNotFoundError, IsADirectoryError:
        return None
    return hashlib.sha256(raw).hexdigest()


def bundled_template_content(template_name: str) -> str | None:
    """Return the text of the currently-installed bundled template, or ``None``."""
    ref = pkg_resources.files("squads._rendering.templates") / template_name
    try:
        return ref.read_text(encoding="utf-8")
    except FileNotFoundError, IsADirectoryError:
        return None


def template_changed_since(template_name: str, base_version: str) -> bool:
    """True when the bundled *template_name* differs between *base_version* and now.

    Returns ``False`` (silent) when the manifest has no record for *base_version*
    or *template_name* — unknown history is treated as unchanged, never as a warning.
    """
    base_hash = template_hash_at_version(template_name, base_version)
    if base_hash is None:
        return False  # No record → assume unchanged (silent)
    current_hash = current_template_hash(template_name)
    if current_hash is None:
        return False  # Template doesn't exist → nothing to compare
    return base_hash != current_hash


def base_version_template_content(template_name: str, base_version: str) -> str | None:
    """Return the content of the bundled template at *base_version*, or ``None``.

    Implementation note: the manifest only stores hashes, not full content — we cannot
    reconstruct arbitrary past content from hashes alone.  When *base_version* equals
    the running version the current bundled content is returned.  For older versions where
    the hash differs from current, we return ``None`` (the diff view will note this).

    This design keeps the manifest lean (hashes only) while still providing the diff for
    the common case (just-upgraded, base-version bundled == previous release).  A richer
    scheme (storing content snapshots) is deliberately deferred.
    """
    current_hash = current_template_hash(template_name)
    base_hash = template_hash_at_version(template_name, base_version)
    if base_hash is not None and base_hash == current_hash:
        # Unchanged since base — current content IS the base content.
        return bundled_template_content(template_name)
    # Changed or unknown — we cannot recover the exact past content.
    return None


def invalidate_cache() -> None:
    """Evict the manifest cache (for tests that need to reload it)."""
    global _manifest_cache
    _manifest_cache = None


def all_bundled_template_names() -> list[str]:
    """Return the sorted list of template names in the current bundled set."""
    manifest = _load_manifest()
    # Collect from all known versions in the manifest to get a complete set.
    all_names: set[str] = set()
    for ver_hashes in manifest.values():
        all_names.update(ver_hashes.keys())
    return sorted(all_names)
