"""Per-release content-hash INDEX + content-addressed STORE for every overridable bundled
artifact — every bundled template plus the bundled spec documents (``workflow.toml``,
``roles.toml``, ``playbook.toml``).

Two JSON documents ship as package data next to the bundled templates, at
``squads._rendering``:

- ``templates_manifest.json`` — the hash INDEX: ``squads_version -> {artifact_key -> sha256_hex}``.
  One version's entry is a **wholesale replacement**, keyed on ``[project].version`` — the
  version bump must land before the entry is regenerated, or the shipped release's own entry
  is overwritten (recoverable from its tag, which is exactly why only the index gets this
  write mode).
- ``content_store.json`` — the content STORE: ``sha256_hex -> normalized text``, deduplicated
  across every artifact key and every release. **Insert-if-absent, then swept to
  reachability** — deliberately distinct from the index's replace semantics, because a
  mis-ordered regeneration must never be able to destroy retained history no tag can restore.
  Never-prune holds to what that reason supports: no revision an index entry names is ever
  removed — a run rewrites only the current version's entry, so a reachability sweep can only
  ever strand a revision that entry alone named, never one a historic entry still names. The
  retention promise: the store's coverage equals the index's coverage, for every release the
  index names, with no window and no expiry.

Both documents are generated by ``scripts/gen_template_manifest.py`` for the running version —
its steady-state contract is "hash the current tree, replace this version's index entry, insert
what is absent from the store, drop every blob no index entry references"; **it never reads
git**. The store's history below the widening release (the index's own floor) was populated
once, as a one-time data step against the release tags (``scripts/seed_content_store.py``), not
a generator capability.

Artifact key namespace — settled at decision level, not an implementer's choice: an entry is
keyed on the artifact's path **relative to the ``squads`` package root**, e.g.
``_rendering/templates/agents/role.md.j2``, ``_specs/workflow.toml``. Every overridable bundled
artifact is package data inside that one package, so the key is unique by construction rather
than by convention, derivable rather than registered, and a fifth kind inherits the namespace
without a dispatch table of its own — the single resolver below walks ``squads`` itself, not a
per-kind lookup. This is the manifest's own on-disk shape: changing it later is a manifest
regeneration (the one-time rekey performed on every historic entry when this namespace was
adopted), not a migration.

Both documents are keyed/hashed on the **same CRLF-normalized bytes** so a Windows checkout
resolves identically to a Linux one.

Hard boundary: this store is provenance for **diffing only**. It is never an input to
validation, to the merge engine, or to the live-corpus cross-check — the corpus remains the
sole authority on what its items were written under.
"""

import hashlib
import importlib.resources as pkg_resources
import json
from importlib.resources.abc import Traversable
from pathlib import PurePosixPath

from squads._util import version_tuple

#: Prefix template keys carry within the package-root namespace.
TEMPLATES_PREFIX = "_rendering/templates/"

#: The three bundled spec documents' package-root-relative keys.
WORKFLOW_KEY = "_specs/workflow.toml"
ROLES_KEY = "_specs/roles.toml"
PLAYBOOK_KEY = "_specs/playbook.toml"

# Cached index/store data.
_manifest_cache: dict[str, dict[str, str]] | None = None
_store_cache: dict[str, str] | None = None


def template_key(template_name: str) -> str:
    """The package-root-relative manifest key for a bundled template.

    ``"items/task.md.j2"`` -> ``"_rendering/templates/items/task.md.j2"``. Every existing caller
    that names a template (scaffold/diff/stamp checks in ``_overrides/_service.py``) keeps using
    the template-relative name; this is the one place that prefix is applied.
    """
    return f"{TEMPLATES_PREFIX}{template_name}"


def _load_manifest() -> dict[str, dict[str, str]]:
    """Load and cache the shipped hash index from package data."""
    global _manifest_cache
    if _manifest_cache is not None:
        return _manifest_cache
    ref = pkg_resources.files("squads._rendering") / "templates_manifest.json"
    try:
        raw = ref.read_text(encoding="utf-8")
        data: dict[str, dict[str, str]] = json.loads(raw)
        _manifest_cache = data
    # Parenthesized (not PEP 758 bare-tuple) so `vulture` can still parse this file;
    # ruff's py314-target formatter would otherwise strip the parens back off.
    except (FileNotFoundError, json.JSONDecodeError):  # fmt: skip
        _manifest_cache = {}
    return _manifest_cache


def _load_store() -> dict[str, str]:
    """Load and cache the shipped content store from package data."""
    global _store_cache
    if _store_cache is not None:
        return _store_cache
    ref = pkg_resources.files("squads._rendering") / "content_store.json"
    try:
        raw = ref.read_text(encoding="utf-8")
        data: dict[str, str] = json.loads(raw)
        _store_cache = data
    except (FileNotFoundError, json.JSONDecodeError):  # fmt: skip
        _store_cache = {}
    return _store_cache


def _resolve_bundled(key: str) -> Traversable:
    """Resolve a package-root-relative *key* against the installed ``squads`` package tree."""
    ref = pkg_resources.files("squads")
    for part in PurePosixPath(key).parts:
        ref = ref / part
    return ref


def _read_bundled_bytes(key: str) -> bytes | None:
    try:
        return _resolve_bundled(key).read_bytes()
    # Parenthesized (not PEP 758 bare-tuple) so `vulture` can still parse this file;
    # ruff's py314-target formatter would otherwise strip the parens back off.
    except (FileNotFoundError, IsADirectoryError):  # fmt: skip
        return None


def _normalize(raw: bytes) -> bytes:
    # Normalize CRLF -> LF before hashing/storing so the digest — and the lookup — are
    # identical on Windows (where git may check out text files as CRLF) and Linux/macOS.
    return raw.replace(b"\r\n", b"\n")


# ─── Generalized artifact resolvers (package-root-relative key) ────────────────


def artifact_hash_at_version(key: str, version: str) -> str | None:
    """Return the SHA-256 hex for *key* as it was in *version*, or ``None``.

    ``None`` means the version, or this particular artifact within that version's entry, is
    not recorded in the index — either because the version predates the index's own floor, or
    because this artifact was not yet an overridable bundled artifact at that release (e.g. a
    spec TOML stamped before it existed).
    """
    manifest = _load_manifest()
    ver_entry = manifest.get(version)
    if ver_entry is None:
        return None
    return ver_entry.get(key)


def current_artifact_hash(key: str) -> str | None:
    """Return the SHA-256 of the currently-installed bundled artifact at *key*, or ``None``."""
    raw = _read_bundled_bytes(key)
    if raw is None:
        return None
    return hashlib.sha256(_normalize(raw)).hexdigest()


def bundled_artifact_content(key: str) -> str | None:
    """Return the (CRLF-normalized) text of the currently-installed bundled artifact, or
    ``None`` when *key* names nothing installed."""
    raw = _read_bundled_bytes(key)
    if raw is None:
        return None
    return _normalize(raw).decode("utf-8")


def artifact_changed_since(key: str, base_version: str) -> bool:
    """True when the bundled artifact at *key* differs between *base_version* and now.

    Returns ``False`` (silent) when the index has no record for *base_version* or *key* —
    "unknown history is treated as unchanged, never as a warning". This
    is what keeps drift content-gated instead of stamp-age-gated for every kind alike.
    """
    base_hash = artifact_hash_at_version(key, base_version)
    if base_hash is None:
        return False
    current_hash = current_artifact_hash(key)
    if current_hash is None:
        return False
    return base_hash != current_hash


def stored_content_for_hash(sha256_hex: str | None) -> str | None:
    """Look up retained content in the content store by its hash, or ``None`` if absent
    (``sha256_hex`` may itself be ``None`` — a convenience for chaining after a lookup that
    can miss)."""
    if sha256_hex is None:
        return None
    return _load_store().get(sha256_hex)


def base_version_artifact_content(key: str, base_version: str) -> str | None:
    """Return the retained content of the bundled artifact at *key* as of *base_version*, or
    ``None`` when that revision is not carried by the store (the uncarried-base case —
    below the index's own floor for this artifact, a malformed stamp, or newer than running)."""
    base_hash = artifact_hash_at_version(key, base_version)
    return stored_content_for_hash(base_hash)


def artifact_floor(key: str) -> str | None:
    """The earliest version whose index entry names *key*, or ``None`` if no version does.

    This is the artifact's *own* floor, not the index's global floor (0.4.0): a spec document
    added partway through the index's history (e.g. ``roles.toml``, first tracked at 0.13.0)
    has a later floor than a template that has been overridable since 0.4.0 — the
    "index did not then cover" case is exactly a stamp older than an artifact's own floor.
    """
    manifest = _load_manifest()
    candidates = [v for v, entry in manifest.items() if key in entry]
    if not candidates:
        return None
    return min(candidates, key=version_tuple)


def known_index_versions() -> list[str]:
    """Every version the shipped index has an entry for, sorted oldest first."""
    return sorted(_load_manifest(), key=version_tuple)


def invalidate_cache() -> None:
    """Evict the index/store caches (for tests that need to reload them)."""
    global _manifest_cache, _store_cache
    _manifest_cache = None
    _store_cache = None


# ─── Template-name convenience wrappers ─────────────────────────────────────────
#
# Every existing caller in `_overrides/_service.py` names a template by its path relative to
# `_rendering/templates/` (e.g. "items/task.md.j2", "agents/role.md.j2") rather than by the full
# package-root-relative key. These wrappers are the one place that translates — not a second
# resolution mechanism, just `template_key()` applied before delegating to the generalized
# `artifact_*` functions above, which is what "no second mechanism beside them"
# asks for: one resolver, walked from two different starting vocabularies.


def template_hash_at_version(template_name: str, version: str) -> str | None:
    """Return the SHA-256 hex for *template_name* as it was in *version*, or ``None``."""
    return artifact_hash_at_version(template_key(template_name), version)


def current_template_hash(template_name: str) -> str | None:
    """Return the SHA-256 of the currently-installed bundled template, or ``None``."""
    return current_artifact_hash(template_key(template_name))


def bundled_template_content(template_name: str) -> str | None:
    """Return the text of the currently-installed bundled template, or ``None``."""
    return bundled_artifact_content(template_key(template_name))


def template_changed_since(template_name: str, base_version: str) -> bool:
    """True when the bundled *template_name* differs between *base_version* and now."""
    return artifact_changed_since(template_key(template_name), base_version)


def base_version_template_content(template_name: str, base_version: str) -> str | None:
    """Return the retained content of the bundled template at *base_version*, or ``None`` when
    that revision is not carried by the store."""
    return base_version_artifact_content(template_key(template_name), base_version)
