"""Backend-neutral ``.index.jsonl`` generator for the lighter-tier content folders.

Agent memory (``squads/agents/memory/<role>/``) and the team bulletin board
(``squads/board/``) both sit *outside* ``.squads.json`` and off the global counter: instead
of an item-model file, each is a folder of slug-named ``.md`` content files with one generated
per-folder ``.index.jsonl`` roll-up. This module is the single generator both features share —
mirroring how ``_backends/_managed_region.py`` is the one shared "regenerate + stamp" mechanism
every backend's managed-region file inherits — rather than each feature re-implementing (and
possibly drifting on) the format.

The index is always regenerated **whole** from the folder's current content files; it is never
appended or hand-edited. JSON Lines: the first line is a header record, every following line is
one entry. Callers own ordering (memory sorts however it likes; the board sorts by its listing
order) — this module only renders/writes/parses, it does not decide entry order.
"""

import json
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

from squads import _aio
from squads._sections import split_frontmatter

INDEX_FILENAME = ".index.jsonl"

#: The `.index.jsonl` format tag — versioned independently of the item `SCHEMA_VERSION` and its
#: migration chain, since these lighter tiers sit outside `.squads.json` entirely.
SCHEMA = "squads.index/1"

#: The generated-file contract (invariant #7) for a JSON-native artifact: a JSONL file can't
#: carry the HTML `<!-- sq:... -->` marker comment, so this plain-text notice in the header's
#: `generated` field plays the same role the managed-region warning plays in CLAUDE.md/AGENTS.md.
#: Names only the paths that actually regenerate the file — there is no in-place edit path.
GENERATED_STAMP = "regenerated by `sq` on add/forget and `sq sync` — do not hand-edit"


@dataclass(frozen=True)
class IndexEntry:
    """One content file's roll-up line: ``{slug, filename, description}``.

    For memory, ``slug`` is the memory's stable slug. For the board, the same field carries a
    notice's stable short-hash id — one schema serves both tiers.
    """

    slug: str
    filename: str
    description: str

    def to_dict(self) -> dict[str, str]:
        return {"slug": self.slug, "filename": self.filename, "description": self.description}


def header_record() -> dict[str, str]:
    """The `.index.jsonl` header line: the format tag plus the do-not-hand-edit stamp."""
    return {"schema": SCHEMA, "generated": GENERATED_STAMP}


def render_index(entries: Iterable[IndexEntry]) -> str:
    """Render the whole `.index.jsonl` text: the header line, then one line per entry.

    Pure and I/O-free — *entries* must already be in the order the caller wants persisted
    (this module does not sort; the board's positional ordinal is literally the entry's line
    position, so sort order is load-bearing and stays the caller's decision).
    """
    lines = [json.dumps(header_record(), sort_keys=False)]
    lines.extend(json.dumps(e.to_dict(), sort_keys=False) for e in entries)
    return "\n".join(lines) + "\n"


def parse_index(text: str) -> tuple[dict[str, str], list[IndexEntry]]:
    """Parse `.index.jsonl` text back into ``(header, entries)``. Empty text -> ``({}, [])``."""
    lines = [ln for ln in text.splitlines() if ln.strip()]
    if not lines:
        return {}, []
    header: dict[str, str] = json.loads(lines[0])
    entries = [IndexEntry(**json.loads(ln)) for ln in lines[1:]]
    return header, entries


async def regenerate(folder: Path, entries: Iterable[IndexEntry]) -> Path:
    """Write *folder*'s ``.index.jsonl`` whole from *entries*. Creates *folder* if missing.

    Returns the index file's path. Called on every add/forget by the owning feature
    (memory today; the board reuses this same function).
    """
    await _aio.mkdir(folder, parents=True, exist_ok=True)
    index_path = folder / INDEX_FILENAME
    await _aio.write_text(index_path, render_index(entries))
    return index_path


async def regenerate_from_content_files(folder: Path) -> Path | None:
    """Rebuild *folder*'s ``.index.jsonl`` whole straight from its current ``.md`` files.

    The one shared entry-builder behind every "regenerate this content-index folder" call
    site — the add/forget mutation path (via :func:`regenerate` directly, since it already
    holds the freshly written entry in memory) and, as of ``sq sync``/``sq repair``, a
    whole-squad maintenance pass that re-derives every folder's index from scratch without
    needing to know what changed. Each entry's ``description`` comes from the content file's
    frontmatter ``summary`` field — the same field both memory entries and board notices use.

    A folder that does not exist on disk is left alone (returns ``None``, writes nothing) —
    nothing to regenerate for a role that has never had a memory added, or a board that has
    never been posted to. This is what makes the maintenance pass safe to run unconditionally
    over every folder the caller knows about, whether or not it has ever been populated.
    """
    if not await _aio.path_exists(folder):
        return None
    paths = await _aio.to_thread(lambda: sorted(folder.glob("*.md")))
    entries: list[IndexEntry] = []
    for path in paths:
        text = await _aio.read_text(path)
        frontmatter, _ = split_frontmatter(text)
        entries.append(
            IndexEntry(
                slug=path.stem,
                filename=path.name,
                description=str(frontmatter.get("summary", "")),
            )
        )
    return await regenerate(folder, entries)
