"""Pluggable agent-backend interface. Claude Code is the first implementation."""

import os
from abc import ABC, abstractmethod
from dataclasses import dataclass
from pathlib import Path

from squads._interactions import skills_for_role
from squads._models._item import Item
from squads._paths import SquadPaths
from squads._roles._catalog import RoleDef
from squads._workflow._models import WorkflowSpec


@dataclass(frozen=True)
class Artifact:
    """A tool-owned file the backend generated (path is project-root-relative)."""

    path: str
    kind: str  # backend-specific category, e.g. agent | skill | config | index
    backend: str
    # Set when writing this artifact surfaced something WARN-only the caller should print —
    # e.g. "inserted the managed region into pre-existing hand-written content". Never gates
    # anything; ``None`` (the common case) means "nothing to report".
    warning: str | None = None


@dataclass(frozen=True)
class RoleView:
    """The roster entry passed to backends (decoupled from RoleDef internals)."""

    slug: str
    full_name: str
    title: str
    is_default: bool


@dataclass(frozen=True)
class OperatorView:
    """A human operator passed to backends for the CLAUDE.md people roster."""

    slug: str
    full_name: str


@dataclass
class BackendContext:
    paths: SquadPaths
    # Slug → absolute body path for already-seeded skill items.  Populated by
    # refresh_managed() from the index before calling write_managed, so backends
    # never need to load the index themselves (layering: _backends reads no index).
    # Empty dict on first-write paths (pre-seeding); skill_paths.get(slug) returns
    # None in that case and the backend falls back to the slug-named temporary path.
    skill_paths: dict[str, Path]
    # Role slug → resolved preload-skill list (system membership unioned with data-driven
    # `scopes` ref edges).  Populated by the service (refresh_managed()/sync()) from the
    # index, same layering rationale as skill_paths: backends read it here rather than
    # resolving scope edges themselves.  Absent entries fall back to the pure
    # `interactions.skills_for_role` in :meth:`resolved_skills_for` — see that method.
    role_skills: dict[str, list[str]]
    # Active workflow spec — supplied by the Service so backends can enumerate custom types.
    # ``None`` means use only built-in types (backward-compatible default for callers that
    # don't supply a spec, e.g. backend conformance tests).
    spec: WorkflowSpec | None

    def __init__(
        self,
        paths: SquadPaths,
        skill_paths: dict[str, Path] | None = None,
        role_skills: dict[str, list[str]] | None = None,
        spec: WorkflowSpec | None = None,
    ) -> None:
        self.paths = paths
        self.skill_paths = skill_paths if skill_paths is not None else {}
        self.role_skills = role_skills if role_skills is not None else {}
        self.spec = spec

    @property
    def root(self) -> Path:
        return self.paths.root

    @property
    def squad_dir(self) -> Path:
        return self.paths.squad_dir

    def rel(self, path: Path) -> str:
        """Root-relative forward-slash path (for Artifact paths and backend-owned references)."""
        return os.path.relpath(path, self.root).replace(os.sep, "/")

    def root_relative(self, item: Item) -> str:
        """Root-relative path to an item's markdown file (for backend-owned file references)."""
        return self.rel(self.paths.abspath(item.path))

    def resolved_skills_for(self, slug: str) -> list[str]:
        """A role's resolved preload-skill list: ``role_skills[slug]`` when populated, else the
        pure system-membership fallback.

        The single read path every backend uses instead of calling
        ``interactions.skills_for_role`` directly, so a data-driven ``scopes`` edge reaches
        every backend uniformly once the service populates ``role_skills`` — never only one.
        """
        if slug in self.role_skills:
            return self.role_skills[slug]
        return skills_for_role(slug)


class AgentBackend(ABC):
    """Contract every agent-tool backend (Claude Code today; a future Copilot/Cursor/
    AGENTS.md-only backend tomorrow) must satisfy.

    Two distinct "don't hand-edit" messages live at two different altitudes, and each backend
    owns stamping the second one:

    1. **Squad data is sq-managed.** Everything under the squad folder (items, role/skill
       bodies) is mutated only via the `sq` CLI. Stated once, globally — not this ABC's concern.
    2. **This backend's own generated agent-facing files are tool-generated by ``sq sync``.**
       Every managed region a backend injects into an otherwise user-owned file (its
       `CLAUDE.md`/`AGENTS.md` section) and every whole file it owns outright (a pointer/config
       file under its own tool directory) MUST carry a "regenerated by `sq sync`; do not edit by
       hand" warning near where an agent or human actually reads it — these are the files an
       agent opens as *working context* and could edit in-session without realizing the edit is
       never safe. Use the shared ``_backends._managed_region`` wrap/inject helpers for a managed
       region so every backend inherits the warning consistently instead of re-implementing it.

    Generated files stay regenerable and are never migrated (deleting one loses nothing) — the
    warning only makes that fact visible in place; it doesn't change the promise.
    """

    name: str

    @abstractmethod
    async def ensure_scaffold(self, ctx: BackendContext) -> list[Artifact]:
        """Create backend dirs and base config (idempotent; never clobber user content)."""

    @abstractmethod
    async def write_managed(
        self, ctx: BackendContext, roster: list[RoleView], operators: list[OperatorView]
    ) -> list[Artifact]:
        """(Re)write roster/version-dependent files: skill definitions and backend config."""

    @abstractmethod
    async def generate_role_entry(self, ctx: BackendContext, item: Item, role: RoleDef) -> Artifact:
        """Write the backend's entry for a role (loads the role's real definition)."""

    @abstractmethod
    async def generate_skill_entry(self, ctx: BackendContext, item: Item) -> Artifact:
        """Write the backend's entry for a skill (loads the skill's real definition)."""

    @abstractmethod
    async def remove_artifacts(self, ctx: BackendContext, item: Item) -> None:
        """Delete the backend entry/entries for an item."""

    @abstractmethod
    async def candidate_orphans(
        self, ctx: BackendContext, roster: list[RoleView], skill_slugs: set[str]
    ) -> list[str]:
        """Root-relative paths of on-disk agent-pointer/skill files this backend does NOT
        currently manage — present on disk but naming no slug in *roster* and no slug in
        *skill_slugs* (the full known-skill vocabulary: every SKILL item plus every
        system/per-type skill the spec implies, regardless of whether this particular run
        happened to rewrite it).

        WARN-only candidates for the caller (``sq init``/``sq adopt``) to report. Read-only:
        must never delete, move, or rewrite anything; a slug match is NOT reported even when
        this exact invocation didn't literally touch that file (e.g. `adopt` only regenerates
        a NEWLY activated role's pointer), because a matching slug is still squads-managed
        territory, not an orphan.
        """

    @abstractmethod
    def managed_paths(self, ctx: BackendContext) -> list[str]:
        """Root-relative paths this backend owns and that sq check expects to exist.

        Read-only: must not create or modify any file.  Returns the same root-relative
        paths that ``ensure_scaffold`` / ``write_managed`` would write, without writing
        them.  Used by ``sq check`` to verify that scaffolding exists (present-only check
        — not a currency/drift check).

        Implementations should scope this to the always-present top-level files whose
        absence means the backend was never scaffolded/synced.
        """
