"""Backend-neutral "managed region" wrapper — markers plus the tool-generated warning.

Every ``AgentBackend`` that maintains a squads-managed section inside an otherwise
user-owned file (``CLAUDE.md``, ``AGENTS.md``, …) delimits that section with the
``squads:start``/``squads:end`` markers and stamps a "regenerated by `sq sync`; do not
edit by hand" warning just inside them — this is the ``AgentBackend`` contract (see its
docstring in ``_base.py``). ``wrap()``/``inject()`` are the shared mechanism so every
backend's managed-region file inherits the warning for free instead of each backend
re-implementing (and possibly forgetting) it; a per-file wrapper
(``_claude_code/_claude_md.py``, ``_agents_md/_managed.py``) only supplies the
file-specific "create if missing" header text.
"""

from pathlib import Path

from squads import _aio

START = "<!-- squads:start -->"
END = "<!-- squads:end -->"
WARNING = "<!-- managed by squads — regenerated by `sq sync`; do not edit by hand. -->"


def wrap(section_body: str) -> str:
    """Delimit *section_body* with the managed markers and the tool-generated warning."""
    return f"{START}\n{WARNING}\n{section_body.rstrip()}\n{END}\n"


async def inject(target: Path, section_body: str, *, missing_header: str) -> None:
    """Insert or replace the managed section in *target*, preserving everything else.

    *missing_header* is prepended only when *target* doesn't exist yet — the caller's
    file-specific scaffold text (e.g. a title line). This module owns only the shared
    marker/warning mechanics; callers own what the rest of their file looks like.
    """
    block = wrap(section_body)
    if not await _aio.path_exists(target):
        await _aio.write_text(target, f"{missing_header}{block}")
        return
    text = await _aio.read_text(target)
    si, ei = text.find(START), text.find(END)
    if si != -1 and ei != -1:
        new = text[:si] + block.rstrip("\n") + text[ei + len(END) :]
        await _aio.write_text(target, new)
    else:
        sep = "" if text.endswith("\n") else "\n"
        await _aio.write_text(target, f"{text}{sep}\n{block}")
